# Generated by Django 2.2.16 on 2022-01-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220109_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name_plural': 'подписки'},
        ),
    ]
